services:
  run_demo:
    image: 'node:lts'
    container_name: demo
    working_dir: /demos/ninjadev/demo
    ports:
      - '3000:3000'
    stop_grace_period: 0s # SIGKILL after 0 seconds (there is no hope for this shutting down in a reasonable time)
    environment:
      CLEAN_BUILD_RENIN: "true"
      CLEAN_BUILD_DEMO: "true"
      EXPORT_AND_HOST_FINAL_VERSION: "false"
    volumes:
      - './:/demos/ninjadev/demo'
      - '../renin:/demos/ninjadev/renin'
    command:
      - /bin/bash
      - -c
      - |
        if [ "$$CLEAN_BUILD_RENIN" == "true" ]; then
          echo "Rebuilding Renin"
          rm -rf /demos/ninjadev/renin/renin/node_modules
          pushd /demos/ninjadev/renin/renin
          yarn install
          yarn build
          popd
          echo "Done rebuilding Renin"
        fi
        if [ "$$CLEAN_BUILD_DEMO" == "true" ] || [ "$$EXPORT_AND_HOST_FINAL_VERSION" == "true" ]; then
          echo "Rebuilding demo"
          rm -rf /demos/ninjadev/demo/node_modules
          rm -rf /demos/ninjadev/demo/dist
          pushd /demos/ninjadev/demo
          yarn install
          popd
          echo "Donre rebuilding demo"
        fi
        if [ "$$EXPORT_AND_HOST_FINAL_VERSION" == "true" ]; then
          echo "Building final version of demo"
          pushd /demos/ninjadev/demo
          yarn build

          echo "Starting hosting of final build of demo on 3000"
          pushd /demos/ninjadev/demo/dist
          python3 -m http.server 3000

          echo "Hosting terminated, exiting container"
          exit
        else
          echo "Hosting demo in dev mode on 3000"
          pushd /demos/ninjadev/demo
          yarn run dev --host --port 3000
        fi
